// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes a given URL for potential security risks using AI.
 *
 * - analyzeUrl - A function that takes a URL as input and returns a risk assessment.
 * - AnalyzeUrlInput - The input type for the analyzeUrl function.
 * - AnalyzeUrlOutput - The return type for the analyzeUrl function, detailing potential risks and confidence levels.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {analyzeUrl as scanUrl} from '@/services/url-scan';

const AnalyzeUrlInputSchema = z.object({
  url: z.string().describe('The URL to analyze for potential risks.'),
});
export type AnalyzeUrlInput = z.infer<typeof AnalyzeUrlInputSchema>;

const AnalyzeUrlOutputSchema = z.object({
  isSafe: z.boolean().describe('Indicates whether the URL is considered safe.'),
  riskReasons: z
    .array(z.string())
    .describe('An array of reasons why the URL might be risky.'),
  confidenceScore: z
    .number()
    .describe('Confidence score for the risk assessment (e.g., 80% risk of phishing).'),
});
export type AnalyzeUrlOutput = z.infer<typeof AnalyzeUrlOutputSchema>;

export async function analyzeUrl(input: AnalyzeUrlInput): Promise<AnalyzeUrlOutput> {
  return analyzeUrlFlow(input);
}

const analyzeUrlPrompt = ai.definePrompt({
  name: 'analyzeUrlPrompt',
  input: {
    schema: z.object({
      url: z.string().describe('The URL to analyze for potential risks.'),
      scanResult: z.object({
        isSafe: z.boolean().describe('Indicates whether the URL is considered safe.'),
        riskReasons: z
          .array(z.string())
          .describe('An array of reasons why the URL might be risky.'),
        confidenceScore: z
          .number()
          .describe('Confidence score for the risk assessment (e.g., 80% risk of phishing).'),
      }),
    }),
  },
  output: {
    schema: AnalyzeUrlOutputSchema,
  },
  prompt: `Analyze the URL {{{url}}} and the following scan result to determine its safety and associated risks.

Scan Result:
Is Safe: {{{scanResult.isSafe}}}
Risk Reasons: {{#each scanResult.riskReasons}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Confidence Score: {{{scanResult.confidenceScore}}}

Based on this information, provide a final risk assessment.

Return the results as a JSON object.
`,
});

const analyzeUrlFlow = ai.defineFlow<
  typeof AnalyzeUrlInputSchema,
  typeof AnalyzeUrlOutputSchema
>({
  name: 'analyzeUrlFlow',
  inputSchema: AnalyzeUrlInputSchema,
  outputSchema: AnalyzeUrlOutputSchema,
},
async input => {
  const scanResult = await scanUrl(input.url);
  const {output} = await analyzeUrlPrompt({
    url: input.url,
    scanResult,
  });
  return output!;
});